### ISSUE TITLE
Release / publish strategy

### ISSUE THREAD

**Issue by aelamrani** [gravitee-io/gravitee-ui-components#273]
The goal of this issue is to define the strategy of releasing / publishing the components.

When the strategy is defined, we will have to work on the integration on Circle CI. 

Detail of implementation is coming then...

https://docs.google.com/presentation/d/1NRGUsJA__fM3eBHez4wvvP2bgUfwRW8EJoQVE8Z-9XA/edit#slide=id.gbd6badfde1_0_1

**Comment by gaetanmaisse** [comment]
Done in:
 - https://github.com/gravitee-io/gravitee-ui-components/pull/287
 - https://github.com/gravitee-io/gravitee-ui-components/pull/290
 - https://github.com/gravitee-io/gravitee-ui-components/pull/292
 - https://github.com/gravitee-io/gravitee-ui-components/pull/293
