### ISSUE TITLE
[gv-select] Options are not properly visible when using it in a `gv-table` 

### ISSUE THREAD

**Issue by aelamrani** [gravitee-io/gravitee-ui-components#329]
![Capture d’écran 2021-04-28 à 09 45 02](https://user-images.githubusercontent.com/1580262/116366520-aa939180-a806-11eb-8671-9c889b6339f7.png)

**Comment by gaetanmaisse** [comment]
Should be addressed as part of https://github.com/gravitee-io/gravitee-ui-components/issues/247
