### ISSUE TITLE
Investigate about an Overlay component

### ISSUE THREAD

**Issue by gaetanmaisse** [gravitee-io/gravitee-ui-components#336]
## Context

Some components like `gv-select` or `gv-autocomplete` are opening panels when focused/used. In the vaste majority of cases everything is working fine but there are some situation where the panel is cropped or displayed under an other element. Technically the panel in like a simple `div` dynamically renderer or not inside the component that why there are sometimes display issues.

After searching a bit it looks like some other frameworks are using an Overlay component to handle that cases, refs:
 - https://github.com/angular/components/tree/master/src/cdk/overlay
 - https://github.com/vaadin/web-components/blob/master/packages/vaadin-overlay/src/vaadin-overlay.js

## Goal

The goal of this issue is to make an investigation on:
 - what would be the real benefit against our current implementation 
 - would it be still relevant if https://github.com/gravitee-io/gravitee-ui-components/issues/251 is done 
 - is it technically doable at an acceptable cost

## Additional info / Comments

For any details discuss with @gcusnieux @gaetanmaisse

**Comment by gaetanmaisse** [comment]
Instead of (re)implementing everything manually, we should rely on a lib that will do the computation for us, `popper.js` could be a good choice: https://popper.js.org.

I give it a try here: https://github.com/gravitee-io/gravitee-ui-components/tree/use-popper

**Comment by gcusnieux** [comment]
Another test, would be to use it to display the gv-select options
