### ISSUE TITLE
Logging configuration buttons not working

### ISSUE THREAD

**Issue by lesjon** [gravitee-io/gravitee-ui-components#520]
**Describe the bug**
When i want to configure the logs to only log the headers i go to Analytics -> Logs -> Configure the logging.
Here i click enable the logging to enable the logging. This works, if i press save i can redeploy and the requests will be logged.
But pressing any of the options under Mode, Content and Scope, don't allow me to save and redeploy and they don't get stored. The logging behavior is not changed.

**To Reproduce**
1. Go to Logging configuration
2. Click on Headers only
3. Scroll down to [SAVE]
4. See error: you cannot save

**Expected behavior**
The expected behavior is that when you change the settings you can save and deploy them.

**Screenshots**
![image](https://user-images.githubusercontent.com/14054043/146519180-fcd75284-5ffc-404b-9fd4-ae11f0f7a328.png)

**Comment by gaetanmaisse** [comment]
@lesjon which version of APIM are you using? 
Because it looks to be the same as https://github.com/gravitee-io/issues/issues/6282 that has been fixed and released in 3.10.6

**Comment by lesjon** [comment]
As far as I can see i am using 3.11.2.

**Comment by mouligno** [comment]
3.11.x is no longer supported, can you update to supported version and see if you still encounter the issue ?
